<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: joi, 3 noiembrie 2022 15:47:40</msg><msg code="0" type="0">comune_PuncteInComune1</msg><msg code="0" type="0">points</msg><msg code="0" type="0">comune</msg><msg code="0" type="0">World Topographic Map</msg><msg code="0" type="0">World Hillshade</msg><msg code="0" type="0">comune_PuncteInComune1</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\_base.py", line 109, in _set
    return setattr(self._arc_object, attr_name, cval(val))
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SCOALA\Master Semestrul 1\M3 - BD Spatiale\Seminar\Proiect\Proiect_BDS\Simbologie.py", line 48, in &lt;module&gt;
    ScriptTool(in_pct_sel=sel_loc)
  File "D:\SCOALA\Master Semestrul 1\M3 - BD Spatiale\Seminar\Proiect\Proiect_BDS\Simbologie.py", line 36, in ScriptTool
    itm.symbol="Star 1"
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\_base.py", line 112, in _set
    raise NameError(
NameError: The attribute 'symbol' is not supported on this instance of Item.
</msg><msg code="0" type="0">Failed script (null)...</msg><msg code="-2147467259" type="100">Failed to execute (SimbologiePuncteComuna).</msg><msg code="0" type="3">Failed at joi, 3 noiembrie 2022 15:47:43 (Elapsed Time: 2,51 seconds)</msg></messages>