<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: vineri, 4 noiembrie 2022 08:48:33</msg><msg code="0" type="0">Se genereaza layerul comune</msg><msg code="0" type="0">Se genereaza layerul puncte</msg><msg code="0" type="0">Se selecteaza punctele dupa clauza COMUNE = 'Rimini'</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "D:\SCOALA\Master Semestrul 1\M3 - BD Spatiale\Seminar\Proiect\Proiect_BDS\PuncteComune.py", line 57, in &lt;module&gt;
    sel_loc_dupa_drum(in_comune=comune,
  File "D:\SCOALA\Master Semestrul 1\M3 - BD Spatiale\Seminar\Proiect\Proiect_BDS\PuncteComune.py", line 24, in sel_loc_dupa_drum
    arcpy.SelectLayerByAttribute_management(in_layer_or_view=puncte_com,
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 10780, in SelectLayerByAttribute
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 10777, in SelectLayerByAttribute
    retval = convertArcObjectToPythonObject(gp.SelectLayerByAttribute_management(*gp_fixargs((in_layer_or_view, selection_type, where_clause, invert_where_clause), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 160144: An expected Field was not found or could not be retrieved properly.
Failed to execute (SelectLayerByAttribute).

</msg><msg code="0" type="0">Failed script (null)...</msg><msg code="-2147467259" type="100">Failed to execute (PuncteInComune).</msg><msg code="0" type="3">Failed at vineri, 4 noiembrie 2022 08:48:33 (Elapsed Time: 0,49 seconds)</msg></messages>